#!/bin/bash

# Settings
export LANG=en_US.UTF-8
export MYSHELL=bash
export EDITOR=vim
export PAGER=less

# Paths
export PREFIX=$HOME/.local
export XDG_CACHE_HOME=$PREFIX/cache
export XDG_CONFIG_HOME=$PREFIX/config
export XDG_DATA_HOME=$PREFIX/share
export XDG_RUNTIME_DIR=$PREFIX/tmp

# App data
export CARGO_HOME=$XDG_DATA_HOME/cargo
export CARGOBIN=$CARGO_HOME/bin
export GOPATH=$XDG_DATA_HOME/go
export GOBIN=$GOPATH/bin
export IPYTHONDIR=$XDG_CONFIG_HOME/ipython
export JULIA_PKGDIR=$XDG_DATA_HOME/julia
export npm_config_prefix=$XDG_DATA_HOME/npm
export NPMBIN=$npm_config_prefix/bin
export MINICONDA_HOME=$XDG_DATA_HOME/miniconda3
export PYLINTHOME=$XDG_DATA_HOME/pylint
export FZFBIN=$XDG_DATA_HOME/fzf/bin

# Config
export HTTPIE_CONFIG_DIR=$XDG_CONFIG_HOME/httpie
export INPUTRC=$XDG_CONFIG_HOME/readline/inputrc
export LESSKEY=$XDG_CONFIG_HOME/less/lesskey
export VIMRC=${XDG_CONFIG_HOME}/vim/vimrc
export VIMINIT="source ${XDG_CONFIG_HOME}/vim/vimrc"
export XINITRC=$XDG_CONFIG_HOME/X11/xinitrc
export TMUX_CONF=$XDG_CONFIG_HOME/tmux/tmux.conf

# Cache
export _FASD_DATA=$XDG_CACHE_HOME/fasd/data
export LESSHISTFILE=$XDG_CACHE_HOME/less/history
export NODE_REPL_HISTORY=$XDG_CACHE_HOME/npm/node_repl_history
export XAUTHORITY=$XDG_CACHE_HOME/X11/Xauthority

# Build PATH
export PATH=$FZFBIN:$GOBIN:$CARGOBIN:$NPMBIN:$PREFIX/bin:/usr/local/bin:/usr/bin:/bin:/sbin/:/usr/local/games:/usr/games
