if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?* ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi
source ~/.zshenv
xmodmap $XDG_CONFIG_HOME/X11/Xmodmap
xrdb -merge $XDG_CONFIG_HOME/X11/Xresources
exec /usr/bin/i3
