if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?* ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Set environment variables.
. ~/.zshenv

xmodmap $XDG_CONFIG_HOME/X11/Xmodmap
xrdb -merge $XDG_CONFIG_HOME/X11/Xresources

if [ -f $XDG_CONFIG_HOME/X11/Xresources-local ] ; then
  . $XDG_CONFIG_HOME/X11/Xresources-local
fi
