if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xrdb -load $XDG_CONFIG_HOME/X11/Xresources
exec xterm -e 'fish -c "tmux new-session -A -s main"'
